from enum import Enum


class RunState(str, Enum):
    INTAKE = "INTAKE"
    SPEC_EXPANSION = "SPEC_EXPANSION"
    BACKLOG_BUILD = "BACKLOG_BUILD"
    TASK_SELECTED = "TASK_SELECTED"
    CONTRACT_NEGOTIATION = "CONTRACT_NEGOTIATION"
    IMPLEMENTING = "IMPLEMENTING"
    STATIC_REVIEW = "STATIC_REVIEW"
    RUNTIME_QA = "RUNTIME_QA"
    REPAIRING = "REPAIRING"
    READY_TO_COMMIT = "READY_TO_COMMIT"
    COMMITTED = "COMMITTED"
    NEXT_TASK = "NEXT_TASK"
    DONE = "DONE"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"

